### ISSUE TITLE
[BUG] Property not foldout after click on triangle

### ISSUE THREAD

**Issue by Racot007** [mackysoft/Unity-SerializeReferenceExtensions#59] opened 2024-06-05 07:56 UTC
### What happened?

Pls watch the video with issue

https://github.com/mackysoft/Unity-SerializeReferenceExtensions/assets/6072592/0bd45e9d-c53a-44d2-a48f-3ebca3d4dd02

### Package Version

1.3.1

### Unity Version

2023.2.20

**Comment by Ziller90** [comment] 2024-07-17 11:20
Same problem!

**Comment by mackysoft** [comment] 2024-08-03 16:22
I have investigated this issue and it appears that the problem is occurring in the layout system after Unity 2022.
It is probably related to the following issue, but I do not know how to address it on my end.
https://github.com/mackysoft/Unity-SerializeReferenceExtensions/issues/57

I have tried to fix the problem, but IMGUI seems to be having difficulty fixing it.

This issue is closed as it is not critical.

**Closed by mackysoft** 2024-08-03 16:22 UTC
Labels: bug

**Comment by Racot007** [comment] 2024-08-05 06:50
No( 
Any plans update to UIElements?

**Comment by mackysoft** [comment] 2024-08-05 06:59
@Racot007 
Hi.
Currently UIElements lacks an API to apply context menus, mainly for properties.
So I will continue to use IMGUI until the necessary APIs are available.
### References
- https://github.com/mackysoft/Unity-SerializeReferenceExtensions/issues/51#issuecomment-2266849134
- https://discussions.unity.com/t/any-plans-for-a-begin-endproperty-equivalent/892424

**Comment by TheShankar** [comment] 2024-09-08 18:39
Just hijacking this as I had the same issue: We can still use the tool normally, just click/double click the field instead of the little arrow!
